select 'acknowledges', pg_size_pretty( pg_total_relation_size(' acknowledges') ) , count(*) from acknowledges union
select 'actions', pg_size_pretty( pg_total_relation_size(' actions') ) , count(*) from actions union
select 'alerts', pg_size_pretty( pg_total_relation_size(' alerts') ) , count(*) from alerts union
select 'application_discovery', pg_size_pretty( pg_total_relation_size(' application_discovery') ) , count(*) from application_discovery union
select 'application_prototype', pg_size_pretty( pg_total_relation_size(' application_prototype') ) , count(*) from application_prototype union
select 'application_template', pg_size_pretty( pg_total_relation_size(' application_template') ) , count(*) from application_template union
select 'applications', pg_size_pretty( pg_total_relation_size(' applications') ) , count(*) from applications union
select 'auditlog', pg_size_pretty( pg_total_relation_size(' auditlog') ) , count(*) from auditlog union
select 'auditlog_details', pg_size_pretty( pg_total_relation_size(' auditlog_details') ) , count(*) from auditlog_details union
select 'autoreg_host', pg_size_pretty( pg_total_relation_size(' autoreg_host') ) , count(*) from autoreg_host union
select 'conditions', pg_size_pretty( pg_total_relation_size(' conditions') ) , count(*) from conditions union
select 'config', pg_size_pretty( pg_total_relation_size(' config') ) , count(*) from config union
select 'config_autoreg_tls', pg_size_pretty( pg_total_relation_size(' config_autoreg_tls') ) , count(*) from config_autoreg_tls union
select 'corr_condition', pg_size_pretty( pg_total_relation_size(' corr_condition') ) , count(*) from corr_condition union
select 'corr_condition_group', pg_size_pretty( pg_total_relation_size(' corr_condition_group') ) , count(*) from corr_condition_group union
select 'corr_condition_tag', pg_size_pretty( pg_total_relation_size(' corr_condition_tag') ) , count(*) from corr_condition_tag union
select 'corr_condition_tagpair', pg_size_pretty( pg_total_relation_size(' corr_condition_tagpair') ) , count(*) from corr_condition_tagpair union
select 'corr_condition_tagvalue', pg_size_pretty( pg_total_relation_size(' corr_condition_tagvalue') ) , count(*) from corr_condition_tagvalue union
select 'corr_operation', pg_size_pretty( pg_total_relation_size(' corr_operation') ) , count(*) from corr_operation union
select 'correlation', pg_size_pretty( pg_total_relation_size(' correlation') ) , count(*) from correlation union
select 'dashboard', pg_size_pretty( pg_total_relation_size(' dashboard') ) , count(*) from dashboard union
select 'dashboard_user', pg_size_pretty( pg_total_relation_size(' dashboard_user') ) , count(*) from dashboard_user union
select 'dashboard_usrgrp', pg_size_pretty( pg_total_relation_size(' dashboard_usrgrp') ) , count(*) from dashboard_usrgrp union
select 'dbversion', pg_size_pretty( pg_total_relation_size(' dbversion') ) , count(*) from dbversion union
select 'dchecks', pg_size_pretty( pg_total_relation_size(' dchecks') ) , count(*) from dchecks union
select 'dhosts', pg_size_pretty( pg_total_relation_size(' dhosts') ) , count(*) from dhosts union
select 'drules', pg_size_pretty( pg_total_relation_size(' drules') ) , count(*) from drules union
select 'dservices', pg_size_pretty( pg_total_relation_size(' dservices') ) , count(*) from dservices union
select 'escalations', pg_size_pretty( pg_total_relation_size(' escalations') ) , count(*) from escalations union
select 'event_recovery', pg_size_pretty( pg_total_relation_size(' event_recovery') ) , count(*) from event_recovery union
select 'event_suppress', pg_size_pretty( pg_total_relation_size(' event_suppress') ) , count(*) from event_suppress union
select 'event_tag', pg_size_pretty( pg_total_relation_size(' event_tag') ) , count(*) from event_tag union
select 'events', pg_size_pretty( pg_total_relation_size(' events') ) , count(*) from events union
select 'expressions', pg_size_pretty( pg_total_relation_size(' expressions') ) , count(*) from expressions union
select 'functions', pg_size_pretty( pg_total_relation_size(' functions') ) , count(*) from functions union
select 'globalmacro', pg_size_pretty( pg_total_relation_size(' globalmacro') ) , count(*) from globalmacro union
select 'globalvars', pg_size_pretty( pg_total_relation_size(' globalvars') ) , count(*) from globalvars union
select 'graph_discovery', pg_size_pretty( pg_total_relation_size(' graph_discovery') ) , count(*) from graph_discovery union
select 'graph_theme', pg_size_pretty( pg_total_relation_size(' graph_theme') ) , count(*) from graph_theme union
select 'graphs', pg_size_pretty( pg_total_relation_size(' graphs') ) , count(*) from graphs union
select 'graphs_items', pg_size_pretty( pg_total_relation_size(' graphs_items') ) , count(*) from graphs_items union
select 'group_discovery', pg_size_pretty( pg_total_relation_size(' group_discovery') ) , count(*) from group_discovery union
select 'group_prototype', pg_size_pretty( pg_total_relation_size(' group_prototype') ) , count(*) from group_prototype union
select 'history', pg_size_pretty( pg_total_relation_size(' history') ) , count(*) from history union
select 'history_log', pg_size_pretty( pg_total_relation_size(' history_log') ) , count(*) from history_log union
select 'history_str', pg_size_pretty( pg_total_relation_size(' history_str') ) , count(*) from history_str union
select 'history_text', pg_size_pretty( pg_total_relation_size(' history_text') ) , count(*) from history_text union
select 'history_uint', pg_size_pretty( pg_total_relation_size(' history_uint') ) , count(*) from history_uint union
select 'host_discovery', pg_size_pretty( pg_total_relation_size(' host_discovery') ) , count(*) from host_discovery union
select 'host_inventory', pg_size_pretty( pg_total_relation_size(' host_inventory') ) , count(*) from host_inventory union
select 'host_tag', pg_size_pretty( pg_total_relation_size(' host_tag') ) , count(*) from host_tag union
select 'hostmacro', pg_size_pretty( pg_total_relation_size(' hostmacro') ) , count(*) from hostmacro union
select 'hosts', pg_size_pretty( pg_total_relation_size(' hosts') ) , count(*) from hosts union
select 'hosts_groups', pg_size_pretty( pg_total_relation_size(' hosts_groups') ) , count(*) from hosts_groups union
select 'hosts_templates', pg_size_pretty( pg_total_relation_size(' hosts_templates') ) , count(*) from hosts_templates union
select 'housekeeper', pg_size_pretty( pg_total_relation_size(' housekeeper') ) , count(*) from housekeeper union
select 'hstgrp', pg_size_pretty( pg_total_relation_size(' hstgrp') ) , count(*) from hstgrp union
select 'httpstep', pg_size_pretty( pg_total_relation_size(' httpstep') ) , count(*) from httpstep union
select 'httpstep_field', pg_size_pretty( pg_total_relation_size(' httpstep_field') ) , count(*) from httpstep_field union
select 'httpstepitem', pg_size_pretty( pg_total_relation_size(' httpstepitem') ) , count(*) from httpstepitem union
select 'httptest', pg_size_pretty( pg_total_relation_size(' httptest') ) , count(*) from httptest union
select 'httptest_field', pg_size_pretty( pg_total_relation_size(' httptest_field') ) , count(*) from httptest_field union
select 'httptestitem', pg_size_pretty( pg_total_relation_size(' httptestitem') ) , count(*) from httptestitem union
select 'icon_map', pg_size_pretty( pg_total_relation_size(' icon_map') ) , count(*) from icon_map union
select 'icon_mapping', pg_size_pretty( pg_total_relation_size(' icon_mapping') ) , count(*) from icon_mapping union
select 'ids', pg_size_pretty( pg_total_relation_size(' ids') ) , count(*) from ids union
select 'images', pg_size_pretty( pg_total_relation_size(' images') ) , count(*) from images union
select 'interface', pg_size_pretty( pg_total_relation_size(' interface') ) , count(*) from interface union
select 'interface_discovery', pg_size_pretty( pg_total_relation_size(' interface_discovery') ) , count(*) from interface_discovery union
select 'interface_snmp', pg_size_pretty( pg_total_relation_size(' interface_snmp') ) , count(*) from interface_snmp union
select 'item_application_prototype', pg_size_pretty( pg_total_relation_size(' item_application_prototype') ) , count(*) from item_application_prototype union
select 'item_condition', pg_size_pretty( pg_total_relation_size(' item_condition') ) , count(*) from item_condition union
select 'item_discovery', pg_size_pretty( pg_total_relation_size(' item_discovery') ) , count(*) from item_discovery union
select 'item_preproc', pg_size_pretty( pg_total_relation_size(' item_preproc') ) , count(*) from item_preproc union
select 'item_rtdata', pg_size_pretty( pg_total_relation_size(' item_rtdata') ) , count(*) from item_rtdata union
select 'items', pg_size_pretty( pg_total_relation_size(' items') ) , count(*) from items union
select 'items_applications', pg_size_pretty( pg_total_relation_size(' items_applications') ) , count(*) from items_applications union
select 'lld_macro_path', pg_size_pretty( pg_total_relation_size(' lld_macro_path') ) , count(*) from lld_macro_path union
select 'lld_override', pg_size_pretty( pg_total_relation_size(' lld_override') ) , count(*) from lld_override union
select 'lld_override_condition', pg_size_pretty( pg_total_relation_size(' lld_override_condition') ) , count(*) from lld_override_condition union
select 'lld_override_opdiscover', pg_size_pretty( pg_total_relation_size(' lld_override_opdiscover') ) , count(*) from lld_override_opdiscover union
select 'lld_override_operation', pg_size_pretty( pg_total_relation_size(' lld_override_operation') ) , count(*) from lld_override_operation union
select 'lld_override_ophistory', pg_size_pretty( pg_total_relation_size(' lld_override_ophistory') ) , count(*) from lld_override_ophistory union
select 'lld_override_opinventory', pg_size_pretty( pg_total_relation_size(' lld_override_opinventory') ) , count(*) from lld_override_opinventory union
select 'lld_override_opperiod', pg_size_pretty( pg_total_relation_size(' lld_override_opperiod') ) , count(*) from lld_override_opperiod union
select 'lld_override_opseverity', pg_size_pretty( pg_total_relation_size(' lld_override_opseverity') ) , count(*) from lld_override_opseverity union
select 'lld_override_opstatus', pg_size_pretty( pg_total_relation_size(' lld_override_opstatus') ) , count(*) from lld_override_opstatus union
select 'lld_override_optag', pg_size_pretty( pg_total_relation_size(' lld_override_optag') ) , count(*) from lld_override_optag union
select 'lld_override_optemplate', pg_size_pretty( pg_total_relation_size(' lld_override_optemplate') ) , count(*) from lld_override_optemplate union
select 'lld_override_optrends', pg_size_pretty( pg_total_relation_size(' lld_override_optrends') ) , count(*) from lld_override_optrends union
select 'maintenance_tag', pg_size_pretty( pg_total_relation_size(' maintenance_tag') ) , count(*) from maintenance_tag union
select 'maintenances', pg_size_pretty( pg_total_relation_size(' maintenances') ) , count(*) from maintenances union
select 'maintenances_groups', pg_size_pretty( pg_total_relation_size(' maintenances_groups') ) , count(*) from maintenances_groups union
select 'maintenances_hosts', pg_size_pretty( pg_total_relation_size(' maintenances_hosts') ) , count(*) from maintenances_hosts union
select 'maintenances_windows', pg_size_pretty( pg_total_relation_size(' maintenances_windows') ) , count(*) from maintenances_windows union
select 'mappings', pg_size_pretty( pg_total_relation_size(' mappings') ) , count(*) from mappings union
select 'media', pg_size_pretty( pg_total_relation_size(' media') ) , count(*) from media union
select 'media_type', pg_size_pretty( pg_total_relation_size(' media_type') ) , count(*) from media_type union
select 'media_type_message', pg_size_pretty( pg_total_relation_size(' media_type_message') ) , count(*) from media_type_message union
select 'media_type_param', pg_size_pretty( pg_total_relation_size(' media_type_param') ) , count(*) from media_type_param union
select 'module', pg_size_pretty( pg_total_relation_size(' module') ) , count(*) from module union
select 'opcommand', pg_size_pretty( pg_total_relation_size(' opcommand') ) , count(*) from opcommand union
select 'opcommand_grp', pg_size_pretty( pg_total_relation_size(' opcommand_grp') ) , count(*) from opcommand_grp union
select 'opcommand_hst', pg_size_pretty( pg_total_relation_size(' opcommand_hst') ) , count(*) from opcommand_hst union
select 'opconditions', pg_size_pretty( pg_total_relation_size(' opconditions') ) , count(*) from opconditions union
select 'operations', pg_size_pretty( pg_total_relation_size(' operations') ) , count(*) from operations union
select 'opgroup', pg_size_pretty( pg_total_relation_size(' opgroup') ) , count(*) from opgroup union
select 'opinventory', pg_size_pretty( pg_total_relation_size(' opinventory') ) , count(*) from opinventory union
select 'opmessage', pg_size_pretty( pg_total_relation_size(' opmessage') ) , count(*) from opmessage union
select 'opmessage_grp', pg_size_pretty( pg_total_relation_size(' opmessage_grp') ) , count(*) from opmessage_grp union
select 'opmessage_usr', pg_size_pretty( pg_total_relation_size(' opmessage_usr') ) , count(*) from opmessage_usr union
select 'optemplate', pg_size_pretty( pg_total_relation_size(' optemplate') ) , count(*) from optemplate union
select 'problem', pg_size_pretty( pg_total_relation_size(' problem') ) , count(*) from problem union
select 'problem_tag', pg_size_pretty( pg_total_relation_size(' problem_tag') ) , count(*) from problem_tag union
select 'profiles', pg_size_pretty( pg_total_relation_size(' profiles') ) , count(*) from profiles union
select 'proxy_autoreg_host', pg_size_pretty( pg_total_relation_size(' proxy_autoreg_host') ) , count(*) from proxy_autoreg_host union
select 'proxy_dhistory', pg_size_pretty( pg_total_relation_size(' proxy_dhistory') ) , count(*) from proxy_dhistory union
select 'proxy_history', pg_size_pretty( pg_total_relation_size(' proxy_history') ) , count(*) from proxy_history union
select 'regexps', pg_size_pretty( pg_total_relation_size(' regexps') ) , count(*) from regexps union
select 'rights', pg_size_pretty( pg_total_relation_size(' rights') ) , count(*) from rights union
select 'screen_user', pg_size_pretty( pg_total_relation_size(' screen_user') ) , count(*) from screen_user union
select 'screen_usrgrp', pg_size_pretty( pg_total_relation_size(' screen_usrgrp') ) , count(*) from screen_usrgrp union
select 'screens', pg_size_pretty( pg_total_relation_size(' screens') ) , count(*) from screens union
select 'screens_items', pg_size_pretty( pg_total_relation_size(' screens_items') ) , count(*) from screens_items union
select 'scripts', pg_size_pretty( pg_total_relation_size(' scripts') ) , count(*) from scripts union
select 'service_alarms', pg_size_pretty( pg_total_relation_size(' service_alarms') ) , count(*) from service_alarms union
select 'services', pg_size_pretty( pg_total_relation_size(' services') ) , count(*) from services union
select 'services_links', pg_size_pretty( pg_total_relation_size(' services_links') ) , count(*) from services_links union
select 'services_times', pg_size_pretty( pg_total_relation_size(' services_times') ) , count(*) from services_times union
select 'sessions', pg_size_pretty( pg_total_relation_size(' sessions') ) , count(*) from sessions union
select 'slides', pg_size_pretty( pg_total_relation_size(' slides') ) , count(*) from slides union
select 'slideshow_user', pg_size_pretty( pg_total_relation_size(' slideshow_user') ) , count(*) from slideshow_user union
select 'slideshow_usrgrp', pg_size_pretty( pg_total_relation_size(' slideshow_usrgrp') ) , count(*) from slideshow_usrgrp union
select 'slideshows', pg_size_pretty( pg_total_relation_size(' slideshows') ) , count(*) from slideshows union
select 'sysmap_element_trigger', pg_size_pretty( pg_total_relation_size(' sysmap_element_trigger') ) , count(*) from sysmap_element_trigger union
select 'sysmap_element_url', pg_size_pretty( pg_total_relation_size(' sysmap_element_url') ) , count(*) from sysmap_element_url union
select 'sysmap_shape', pg_size_pretty( pg_total_relation_size(' sysmap_shape') ) , count(*) from sysmap_shape union
select 'sysmap_url', pg_size_pretty( pg_total_relation_size(' sysmap_url') ) , count(*) from sysmap_url union
select 'sysmap_user', pg_size_pretty( pg_total_relation_size(' sysmap_user') ) , count(*) from sysmap_user union
select 'sysmap_usrgrp', pg_size_pretty( pg_total_relation_size(' sysmap_usrgrp') ) , count(*) from sysmap_usrgrp union
select 'sysmaps', pg_size_pretty( pg_total_relation_size(' sysmaps') ) , count(*) from sysmaps union
select 'sysmaps_elements', pg_size_pretty( pg_total_relation_size(' sysmaps_elements') ) , count(*) from sysmaps_elements union
select 'sysmaps_link_triggers', pg_size_pretty( pg_total_relation_size(' sysmaps_link_triggers') ) , count(*) from sysmaps_link_triggers union
select 'sysmaps_links', pg_size_pretty( pg_total_relation_size(' sysmaps_links') ) , count(*) from sysmaps_links union
select 'tag_filter', pg_size_pretty( pg_total_relation_size(' tag_filter') ) , count(*) from tag_filter union
select 'task', pg_size_pretty( pg_total_relation_size(' task') ) , count(*) from task union
select 'task_acknowledge', pg_size_pretty( pg_total_relation_size(' task_acknowledge') ) , count(*) from task_acknowledge union
select 'task_check_now', pg_size_pretty( pg_total_relation_size(' task_check_now') ) , count(*) from task_check_now union
select 'task_close_problem', pg_size_pretty( pg_total_relation_size(' task_close_problem') ) , count(*) from task_close_problem union
select 'task_data', pg_size_pretty( pg_total_relation_size(' task_data') ) , count(*) from task_data union
select 'task_remote_command', pg_size_pretty( pg_total_relation_size(' task_remote_command') ) , count(*) from task_remote_command union
select 'task_remote_command_result', pg_size_pretty( pg_total_relation_size(' task_remote_command_result') ) , count(*) from task_remote_command_result union
select 'task_result', pg_size_pretty( pg_total_relation_size(' task_result') ) , count(*) from task_result union
select 'timeperiods', pg_size_pretty( pg_total_relation_size(' timeperiods') ) , count(*) from timeperiods union
select 'trends', pg_size_pretty( pg_total_relation_size(' trends') ) , count(*) from trends union
select 'trends_uint', pg_size_pretty( pg_total_relation_size(' trends_uint') ) , count(*) from trends_uint union
select 'trigger_depends', pg_size_pretty( pg_total_relation_size(' trigger_depends') ) , count(*) from trigger_depends union
select 'trigger_discovery', pg_size_pretty( pg_total_relation_size(' trigger_discovery') ) , count(*) from trigger_discovery union
select 'trigger_tag', pg_size_pretty( pg_total_relation_size(' trigger_tag') ) , count(*) from trigger_tag union
select 'triggers', pg_size_pretty( pg_total_relation_size(' triggers') ) , count(*) from triggers union
select 'users', pg_size_pretty( pg_total_relation_size(' users') ) , count(*) from users union
select 'users_groups', pg_size_pretty( pg_total_relation_size(' users_groups') ) , count(*) from users_groups union
select 'usrgrp', pg_size_pretty( pg_total_relation_size(' usrgrp') ) , count(*) from usrgrp union
select 'valuemaps', pg_size_pretty( pg_total_relation_size(' valuemaps') ) , count(*) from valuemaps union
select 'widget', pg_size_pretty( pg_total_relation_size(' widget') ) , count(*) from widget union
select 'widget_field', pg_size_pretty( pg_total_relation_size(' widget_field') ) , count(*) from widget_field;
